name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Svelte app
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_WEBSITE_7F103 }}  # Replace with your Firebase service account secret
          projectId: portfolio-website-7f103  # Replace with your Firebase project ID

      # Additional steps if needed, such as running tests or other build tasks
